#!/usr/bin/env bash
# install-sslh.sh — Install and configure sslh on the BJHUNT VPS
#
# Per docs/architecture/13-VPS-CONFIG.md and 12-DOCKER-DEPLOYMENT.md:
# sslh listens on TCP/443 and routes traffic by protocol fingerprint:
#   - SSH handshake → forward to localhost:22 (or whatever sshd listens on)
#   - TLS handshake → forward to localhost:8443 (Caddy)
#
# This unblocks port 443 multiplexing, required because the VPS provider
# blocks all ports except 80 and 443.
#
# RUN AS ROOT on the VPS:
#   sudo bash ops/scripts/install-sslh.sh
#
# After running, the docker-compose.yml change "8443:443" for caddy will work.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: Must run as root (sudo bash $0)"
    exit 1
fi

echo "=== Phase 1 — Move sshd to port 22 (currently 443) ==="
SSHD_CONFIG=/etc/ssh/sshd_config

if grep -qE "^Port 443" "$SSHD_CONFIG"; then
    cp "$SSHD_CONFIG" "${SSHD_CONFIG}.pre-sslh.bak"
    sed -i 's/^Port 443/Port 22/' "$SSHD_CONFIG"
    echo "Patched sshd_config: Port 443 → Port 22 (backup at ${SSHD_CONFIG}.pre-sslh.bak)"

    # CRITICAL: open a backup session before reloading sshd
    echo ""
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo "!! IMPORTANT: Open a SECOND ssh session NOW on port 22 BEFORE"
    echo "!! restarting sshd, in case anything goes wrong."
    echo "!!"
    echo "!!   ssh -p 22 root@82.25.117.79"
    echo "!!"
    echo "!! Press ENTER once you have a working second session."
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    read -r
    systemctl reload sshd
else
    echo "sshd already not on port 443, skipping sshd reconfiguration."
fi

echo ""
echo "=== Phase 2 — Install sslh ==="
apt-get update
apt-get install -y sslh

echo ""
echo "=== Phase 3 — Configure sslh (standalone mode on :443) ==="
cat > /etc/default/sslh <<'EOF'
# /etc/default/sslh — generated by ops/scripts/install-sslh.sh
RUN=yes
DAEMON=/usr/sbin/sslh
DAEMON_OPTS="--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --tls 127.0.0.1:8443 --pidfile /var/run/sslh/sslh.pid"
EOF

# Override systemd to use standalone mode (not the libwrap variant)
mkdir -p /etc/systemd/system/sslh.service.d
cat > /etc/systemd/system/sslh.service.d/override.conf <<'EOF'
[Service]
ExecStart=
ExecStart=/usr/sbin/sslh --foreground --user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --tls 127.0.0.1:8443
EOF

systemctl daemon-reload
systemctl enable sslh
systemctl restart sslh

echo ""
echo "=== Phase 4 — Verify ==="
sleep 2
if systemctl is-active --quiet sslh; then
    echo "sslh is RUNNING"
else
    echo "ERROR: sslh failed to start. Check 'journalctl -u sslh -n 50'"
    exit 1
fi

ss -tlnp | grep -E ":(443|22|8443)\s" || true

echo ""
echo "=== DONE ==="
echo "sslh is now multiplexing TCP/443:"
echo "  - SSH traffic → 127.0.0.1:22 (sshd)"
echo "  - TLS traffic → 127.0.0.1:8443 (Caddy when deployed)"
echo ""
echo "From your laptop, both should now work:"
echo "  ssh -p 443 root@82.25.117.79     # SSH multiplexed"
echo "  curl -v https://api.bjhunt.com/  # HTTPS (once Caddy listens on 8443 inside container)"
echo ""
echo "Next step: deploy the docker-compose.yml change (caddy: 8443:443)."
